import type { Metadata } from 'next';
import { GuidePage } from '@/components/guides/guide-page';

const path = '/guides/equal-vs-unequal-bill-splitting';
const title = 'Equal vs Unequal Bill Splitting';
const description = 'Compare equal, item-based and proportional ways to split a bill, including tips, shared charges and rounding.';
export const metadata: Metadata = { title: { absolute: `${title} | Zalea Studio` }, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: 'article' }, twitter: { card: 'summary', title, description } };

export default function BillSplittingGuidePage() {
  return <GuidePage title={title} description={description} path={path} eyebrow="Everyday decisions guide" relatedLinks={[
    { label: 'Split Bill Calculator', href: '/finance/split-bill-calculator', description: 'Divide an agreed equal total and optional tip between the group.' },
    { label: 'Percentage Calculator', href: '/math/percentage-calculator', description: 'Work out a tip rate or proportional share.' },
    { label: 'All Finance Tools', href: '/finance', description: 'Explore calculators for purchases, savings and everyday costs.' },
  ]}>
    <section><h2 className="text-3xl font-bold tracking-tight">Fair does not always mean equal</h2><p className="mt-4 leading-7 text-muted-foreground">An equal split is simple: add the shared total and divide by the number of people. It works well when everyone ordered or used roughly the same amount and the group agrees that small differences do not matter. An unequal split is more suitable when individual spending differs enough that equal shares would surprise someone.</p><p className="mt-4 leading-7 text-muted-foreground">The best method is usually the one discussed before payment. A quick agreement avoids making one person reconstruct every item while others are ready to leave.</p></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Three practical methods</h2><div className="mt-6 space-y-5"><Method title="Equal split" best="Best when spending is similar and everyone agrees.">Add the bill, any agreed tip and charges, then divide the total by the number of people.</Method><Method title="Item-based split" best="Best when orders differ clearly.">Assign each personal item to the person who ordered it. Divide shared dishes and common fees separately.</Method><Method title="Proportional split" best="Best when a shared charge should follow each person’s spending.">Find each person’s subtotal as a share of all subtotals, then apply that proportion to tax, service or another shared charge.</Method></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Worked example: different meals, shared dessert</h2><p className="mt-4 leading-7 text-muted-foreground">Three people order meals costing RM24, RM36 and RM30. They also share a RM15 dessert equally. Before service, their shares are RM29, RM41 and RM35. If the receipt includes a RM10 service charge and the group agrees to divide that equally, add RM3.33, RM3.33 and RM3.34 so the rounded payments still match the total.</p><div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-6 text-sm leading-7"><p><strong>Personal meals:</strong> RM24 + RM36 + RM30 = RM90</p><p><strong>Dessert:</strong> RM15 ÷ 3 = RM5 each</p><p><strong>Total receipt:</strong> RM90 + RM15 + RM10 = RM115</p></div><p className="mt-4 leading-7 text-muted-foreground">If everyone had spent about the same amount, entering RM105 and a RM10 tip or charge into the equal <strong>Split Bill Calculator</strong> would be faster. For this example, item-based shares preserve the meaningful difference between meals.</p></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">Handle tips and charges clearly</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Check whether a service charge is already included before adding a tip.</li><li>Agree whether a tip is divided equally or follows individual subtotals.</li><li>Separate delivery fees or discounts only when the group considers that worthwhile.</li><li>When shares round to cents, adjust one payment by the small remainder.</li></ul></div><div><h2 className="text-3xl font-bold tracking-tight">Common misunderstandings</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Equal splitting is not automatically fair when one order is much larger.</li><li>Itemising every small difference can take more effort than the group values.</li><li>A 10% tip is calculated from the agreed base amount, not simply added as ten currency units.</li><li>Rounding each share down can leave the person paying short.</li></ul></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">A low-friction group routine</h2><p className="mt-4 leading-7 text-muted-foreground">Ask whether anyone has a clearly different order. If not, confirm an equal split. If yes, total personal items, name which items are shared, decide how to handle charges and show the final shares before collecting payment. The aim is clarity, not mathematical perfection over differences the group does not care about.</p></section>
  </GuidePage>;
}

function Method({ title, best, children }: { title: string; best: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-border/60 bg-card p-6"><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 font-medium text-primary">{best}</p><p className="mt-3 leading-7 text-muted-foreground">{children}</p></div>; }
