import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ClipboardCheck, GraduationCap, Scale, School, Target } from 'lucide-react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { educationTools } from '@/lib/education-tools';

const title = 'Free Education Calculators & Student Tools | Zalea Studio';
const description = 'Free and easy-to-use education tools for students, parents and teachers. Calculate grades, exam scores, GPA and more without signing up.';

export const metadata: Metadata = {
  title: { absolute: title },
  description,
  alternates: { canonical: '/education' },
  openGraph: { title, description, url: '/education', type: 'website' },
};

const icons = { 'graduation-cap': GraduationCap, target: Target, scale: Scale, school: School, 'clipboard-check': ClipboardCheck };

export default function EducationToolsPage() {
  return <div className="min-h-screen bg-background"><SiteHeader /><main>
    <section className="border-b border-border/60 bg-gradient-to-b from-blue-50/70 to-background"><div className="mx-auto max-w-[1200px] px-4 py-16 text-center sm:px-6 lg:px-8 lg:py-24"><Badge variant="secondary" className="border-primary/20 bg-primary/10 text-primary">Free student tools</Badge><h1 className="mx-auto mt-5 max-w-4xl text-balance text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Education Calculators &amp; Student Tools</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">{description}</p></div></section>
    <section className="mx-auto max-w-[1200px] px-4 py-16 sm:px-6 lg:px-8 lg:py-24" aria-labelledby="education-calculators-heading"><div className="mb-10"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Choose a calculator</p><h2 id="education-calculators-heading" className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Available education tools</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{educationTools.map((tool) => { const Icon = icons[tool.icon]; return <Link key={tool.slug} href={`/education/${tool.slug}`} className="group rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><Card className="h-full border-border/60 shadow-sm transition-all group-hover:-translate-y-1 group-hover:shadow-md"><CardHeader><span className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-6 w-6" aria-hidden="true" /></span><CardTitle className="flex items-center justify-between gap-3 text-xl">{tool.title}<ArrowRight className="h-5 w-5 shrink-0 text-primary transition-transform group-hover:translate-x-1" aria-hidden="true" /></CardTitle></CardHeader><CardContent><p className="leading-relaxed text-muted-foreground">{tool.description}</p></CardContent></Card></Link>; })}</div></section>
    <section className="border-y border-border/60 bg-secondary/30"><div className="mx-auto max-w-[1100px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Choose by question</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Which grade calculator should you use?</h2><p className="mt-4 leading-relaxed text-muted-foreground">The best tool depends on what your teacher or course has given you: raw points, weighted categories, credit hours, or a target for an upcoming final exam.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Add assignment scores</h3><p className="mt-3 leading-relaxed text-muted-foreground">Use the <Link href="/education/grade-calculator" className="font-semibold text-primary hover:underline">Grade Calculator</Link> when you know points earned and points possible. For a single test, the <Link href="/education/test-grade-calculator" className="font-semibold text-primary hover:underline">Test Grade Calculator</Link> also produces a complete score chart.</p></div><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Work with percentages</h3><p className="mt-3 leading-relaxed text-muted-foreground">Choose the <Link href="/education/weighted-grade-calculator" className="font-semibold text-primary hover:underline">Weighted Grade Calculator</Link> when exams, homework or other categories contribute different percentages to the course total.</p></div><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Plan an academic target</h3><p className="mt-3 leading-relaxed text-muted-foreground">Use the <Link href="/education/final-grade-calculator" className="font-semibold text-primary hover:underline">Final Grade Calculator</Link> to estimate the exam score needed for a target, or the <Link href="/education/gpa-calculator" className="font-semibold text-primary hover:underline">GPA Calculator</Link> for letter grades and credit hours.</p></div></div></div></section>
    <section className="mx-auto max-w-[1000px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">Check the grading method first</h2><p className="mt-4 leading-relaxed text-muted-foreground">A calculator can only follow the grading structure entered. Before relying on a result, check whether your course uses total points, category weights, dropped assignments, extra credit, or a particular GPA scale. Keep units consistent and make sure percentage weights represent the full course.</p><p className="mt-4 leading-relaxed text-muted-foreground">The result is most useful as a planning estimate: compare it with the gradebook, then update missing or provisional scores as they become available.</p></div><aside className="rounded-2xl border border-blue-200 bg-blue-50/60 p-6 sm:p-8" aria-labelledby="education-policy-note"><h2 id="education-policy-note" className="text-2xl font-bold">Schools use different policies</h2><p className="mt-4 leading-relaxed text-muted-foreground">Letter-grade boundaries, GPA points, rounding, resits and extra-credit rules vary between schools and courses. These tools use the values shown on each calculator page and do not replace an institution&apos;s official grade calculation.</p></aside></div></section>
  </main><SiteFooter /></div>;
}

