import Link from 'next/link';
import { ArrowRight, BookOpen, CheckCircle2, MessageCircle, Sparkles } from 'lucide-react';
import { EducationHubLayout } from '@/components/education-hub-layout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { englishGames } from '@/lib/games/english-games';
import { createEducationalMetadata } from '@/lib/seo';

export const metadata = createEducationalMetadata({
  title: 'Grammar Guide for Kids – Examples and Practice | Zalea Studio',
  description: 'A practical guide to teaching early grammar through meaning, examples and low-pressure practice, with free games for reviewing each concept.',
  path: '/grammar-games-for-kids',
});

export default function GrammarGamesForKidsPage() {
  return <EducationHubLayout eyebrow="Grammar learning guide" title="Grammar Games for Kids" introduction="Grammar helps words work together so a sentence communicates a clear idea. This guide explains practical ways to teach early grammar through meaning, examples and conversation, with Zalea’s free games available afterward for short practice sessions.">
    <section className="mx-auto max-w-[1000px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20">
      <div className="max-w-3xl"><BookOpen className="h-9 w-9 text-primary" aria-hidden="true" /><h2 className="mt-4 text-3xl font-bold tracking-tight">Teach the meaning before the label</h2><p className="mt-4 leading-relaxed text-muted-foreground">Young learners do not need a long definition before they can notice how grammar changes meaning. Begin with two short examples, talk about what each sentence tells us, and only then introduce a term such as <em>plural</em>, <em>pronoun</em> or <em>preposition</em>. “One cat” and “two cats” makes the idea of singular and plural concrete before a rule is memorised.</p><p className="mt-4 leading-relaxed text-muted-foreground">Use familiar people, objects and actions. A sentence about a cup under a chair is easier to test in real life than an abstract worksheet sentence. Once the child understands the contrast, vary one part at a time: “The cup is on the chair,” “The cup is behind the chair,” and “The cups are behind the chair.”</p></div>
      <div className="mt-10 grid gap-5 md:grid-cols-3">
        <GuideCard icon={<MessageCircle className="h-6 w-6" aria-hidden="true" />} title="Hear and discuss">Say complete examples aloud and ask what changed. Conversation connects the sentence to its meaning.</GuideCard>
        <GuideCard icon={<CheckCircle2 className="h-6 w-6" aria-hidden="true" />} title="Choose and explain">Offer two sensible choices, then ask the child to explain the clue instead of guessing repeatedly.</GuideCard>
        <GuideCard icon={<Sparkles className="h-6 w-6" aria-hidden="true" />} title="Use it independently">Move from selecting an answer to saying or writing a new sentence with the same pattern.</GuideCard>
      </div>
    </section>

    <section className="border-y border-border/60 bg-secondary/30"><div className="mx-auto grid max-w-[1000px] gap-8 px-4 py-14 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-20">
      <div><h2 className="text-3xl font-bold tracking-tight">Early grammar concepts in context</h2><div className="mt-6 space-y-5 leading-relaxed text-muted-foreground"><p><strong className="text-foreground">Articles:</strong> use <em>a</em> before a consonant sound and <em>an</em> before a vowel sound: “a dog,” “an apple,” and “an hour.” The sound matters, not simply the first written letter.</p><p><strong className="text-foreground">Agreement:</strong> sentence parts need to match. We say “I am ready,” “She is ready,” and “They are ready.” With <em>have</em>, compare “He has a book” and “They have books.”</p><p><strong className="text-foreground">Reference words:</strong> pronouns and demonstratives help speakers avoid repeating names and show who or what they mean: “Maya has a kite. She flies it,” or “this cup” nearby and “that cup” farther away.</p><p><strong className="text-foreground">Position and possession:</strong> prepositions locate something—“under the table”—while possessive words show a relationship—“her pencil” or “their bag.”</p></div></div>
      <div><h2 className="text-3xl font-bold tracking-tight">Common mistakes to work through</h2><ul className="mt-6 list-disc space-y-4 pl-5 leading-relaxed text-muted-foreground"><li><strong className="text-foreground">Choosing by spelling alone:</strong> <em>an hour</em> begins with a vowel sound even though <em>hour</em> begins with the letter h.</li><li><strong className="text-foreground">Over-applying a plural rule:</strong> adding <em>-s</em> works for many words, but words such as <em>child/children</em> need to be learned through repeated examples.</li><li><strong className="text-foreground">Mixing subject and verb forms:</strong> “She are” often means the learner has not yet connected the subject with the matching form. Contrast two complete sentences rather than correcting one word in isolation.</li><li><strong className="text-foreground">Stopping at recognition:</strong> selecting <em>under</em> from two answers is useful, but asking the child to place a toy and describe it shows whether they can use the word independently.</li></ul></div>
    </div></section>

    <section className="mx-auto max-w-[1000px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">A simple practice routine</h2><ol className="mt-6 space-y-4 text-muted-foreground"><li><strong className="block text-foreground">1. Model two examples.</strong> Keep the vocabulary easy so the grammar is the only new part.</li><li><strong className="block text-foreground">2. Notice the contrast.</strong> Ask what changed and what that change tells the listener.</li><li><strong className="block text-foreground">3. Try a supported choice.</strong> Let the child select between two forms and explain the clue.</li><li><strong className="block text-foreground">4. Make a fresh sentence.</strong> Change the person, object or place and ask the child to complete or create the sentence.</li><li><strong className="block text-foreground">5. Revisit later.</strong> A short return on another day is usually more useful than turning one mistake into a long test.</li></ol></div><div><h2 className="text-3xl font-bold tracking-tight">Keep correction low-pressure</h2><p className="mt-4 leading-relaxed text-muted-foreground">When a child says “He have a ball,” respond with the correct form naturally—“Yes, he has a ball”—and give another chance in a new sentence. Ask for an explanation when it helps, but avoid requiring the child to repeat a correction many times.</p><p className="mt-4 leading-relaxed text-muted-foreground">Look for patterns across several examples. A single slip may come from rushing, while the same choice in different contexts may show which contrast needs more practice. Games can provide repetition, but reading together, everyday conversation and the child&apos;s own sentences are what connect a rule to real language.</p></div></div></section>

    <section className="border-y border-border/60 bg-background"><div className="mx-auto max-w-[1100px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-3xl"><h2 className="text-3xl font-bold tracking-tight">Free Grammar Level 1 practice games</h2><p className="mt-4 leading-relaxed text-muted-foreground">Use these activities after introducing a concept, or return to one for a short review. The collection covers articles, plurals, personal pronouns, forms of “to be”, ability, possessive words, prepositions, demonstratives and has/have. Each game offers Easy, Normal and Challenge modes without requiring an account.</p></div>
      <div className="mt-9 grid gap-5 md:grid-cols-2">{englishGames.map((game) => <Card key={game.slug}><CardHeader><div className="flex items-center gap-3"><span className="text-2xl" aria-hidden="true">{game.icon}</span><CardTitle className="text-xl">{game.title}</CardTitle></div></CardHeader><CardContent><p className="leading-relaxed text-muted-foreground">{game.shortDescription} {game.learningObjective}</p><Link href={`/games/english/${game.slug}`} className="mt-4 inline-flex min-h-11 items-center font-semibold text-primary hover:underline">Play {game.title}<ArrowRight className="ml-1 h-4 w-4" aria-hidden="true" /></Link></CardContent></Card>)}</div>
    </div></section>
    <section className="border-y border-violet-200 bg-violet-50/70"><div className="mx-auto max-w-3xl px-4 py-14 text-center sm:px-6 lg:px-8"><Sparkles className="mx-auto h-9 w-9 text-violet-700" aria-hidden="true" /><h2 className="mt-4 text-3xl font-bold text-violet-950">What comes after Level 1?</h2><p className="mt-4 leading-relaxed text-violet-900">Grammar Level 2 in Zalea English Academy introduces past forms, helping verbs, negatives, verb endings, question words, conjunctions, time prepositions and sentence building. The protected questions are available only after a valid Lifetime Access licence is verified.</p><Button asChild size="lg" className="mt-7 min-h-12 bg-violet-700 hover:bg-violet-800"><Link href="/games/english/academy">Explore Zalea English Academy<ArrowRight className="ml-2 h-5 w-5" aria-hidden="true" /></Link></Button><p className="mt-5 text-sm"><Link href="/english-games-for-kids" className="font-semibold text-violet-800 hover:underline">Read the English games guide</Link></p></div></section>
  </EducationHubLayout>;
}

function GuideCard({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return <Card className="border-border/60 shadow-sm"><CardHeader><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><CardTitle className="pt-2 text-xl">{title}</CardTitle></CardHeader><CardContent className="leading-relaxed text-muted-foreground">{children}</CardContent></Card>;
}
