export const freebieCategories = {
  'school-study': {
    label: 'School & Study',
    description: 'Simple planners and trackers for students, teachers and families.',
  },
  'kids-early-learning': {
    label: 'Kids & Early Learning',
    description: 'Friendly printable activities for growing early skills.',
  },
  'money-budgeting': {
    label: 'Money & Budgeting',
    description: 'Practical printables for saving, budgeting and money goals.',
  },
} as const;

export type FreebieCategory = keyof typeof freebieCategories;

export type FreebieRelatedLink = {
  label: string;
  href: string;
  description?: string;
};

export type Freebie = {
  slug: string;
  title: string;
  shortTitle: string;
  longTitle?: string;
  description: string;
  category: FreebieCategory;
  audience: string;
  ageRange?: string;
  pageCount: number;
  format: string;
  featured: boolean;
  published: boolean;
  previewImage?: string;
  a4Download: string;
  usLetterDownload: string;
  bundleDownload: string;
  bundleFormat: 'ZIP';
  includedPages: readonly string[];
  helpsTitle: string;
  helpsWith: readonly string[];
  howToUse: readonly string[];
  practicalTips: readonly string[];
  whoItsFor: string;
  relatedFreebies: readonly string[];
  relatedLinks: readonly FreebieRelatedLink[];
  seoTitle: string;
  seoDescription: string;
  notice?: string;
};

const downloadRoot = '/downloads/freebies';

export const freebies: readonly Freebie[] = [
  {
    slug: 'shapes-and-colours-activity-pack',
    title: 'Shapes & Colours Activity Pack',
    shortTitle: 'Shapes & Colours',
    description: 'Practise recognising, tracing, matching and sorting familiar shapes and colours through playful activities.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 20,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/shapes-and-colours-activity-pack/Zalea_Shapes_and_Colours_Activity_Pack_20_Pages_A4.pdf`,
    usLetterDownload: `${downloadRoot}/shapes-and-colours-activity-pack/Zalea_Shapes_and_Colours_Activity_Pack_20_Pages_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/shapes-and-colours-activity-pack/Zalea_Shapes_and_Colours_Activity_Pack_20_Pages.zip`,
    bundleFormat: 'ZIP',
    includedPages: [
      'Cover',
      'Before You Begin Guide',
      'Eight Shape Tracing Activities',
      'Five Colour-Matching Activities',
      'Match the Shapes',
      'Match the Colours',
      'Shapes & Colour Patterns',
      'Cut and Paste',
      'Shapes & Colours Star Certificate',
    ],
    helpsTitle: 'What These Shape and Colour Activities Help Children Practise',
    helpsWith: [
      'Introduce circles, squares, triangles, rectangles, ovals, diamonds, stars and hearts through tracing and visual-search activities. Children can notice outlines, sides and curves while looking for matching examples.',
      'Colour pages cover red, orange, yellow, green, blue, purple, pink, brown, black and white before moving into shape matching, colour matching, simple patterns and a cut-and-paste review.',
    ],
    howToUse: [
      'Name the featured shape or colour together before starting each activity.',
      'Let the child trace, point and describe what they notice before marking an answer.',
      'Connect the page to familiar objects such as round plates, rectangular books or coloured toys.',
      'Use the matching and pattern pages after the individual shapes and colours feel familiar.',
    ],
    practicalTips: [
      'Practise one or two pages at a time and revisit favourites later.',
      'Invite the child to find the same shape or colour around the room.',
      'Supervise the final cut-and-paste activity and use child-safe scissors.',
    ],
    whoItsFor: 'Designed for parents and preschool teachers introducing familiar shapes, colours, matching and simple patterns to children ages 3–5.',
    relatedFreebies: ['numbers-1-10-activity-pack', 'pre-writing-pencil-control', 'scissor-skills-practice'],
    relatedLinks: [],
    seoTitle: 'Free Shapes & Colours Activity Pack | Zalea Studio',
    seoDescription: 'Download 20 printable shapes and colours activities for ages 3–5, with tracing, matching, patterns and a supervised cut-and-paste activity.',
    notice: 'Grown-up supervision is required for the cut-and-paste page. Use child-safe scissors and provide help appropriate to the child’s experience.',
  },
  {
    slug: 'numbers-1-10-activity-pack',
    title: 'Numbers 1–10 Activity Pack',
    shortTitle: 'Numbers 1–10',
    description: 'Connect numbers with real quantities through tracing, counting, matching and simple number activities.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 20,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/numbers-1-10-activity-pack/Zalea_Numbers_1-10_Activity_Pack_20_Pages_A4.pdf`,
    usLetterDownload: `${downloadRoot}/numbers-1-10-activity-pack/Zalea_Numbers_1-10_Activity_Pack_20_Pages_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/numbers-1-10-activity-pack/Zalea_Numbers_1-10_Activity_Pack_20_Pages.zip`,
    bundleFormat: 'ZIP',
    includedPages: [
      'Cover',
      'Before You Begin Guide',
      'Numbers 1–10 Tracing and Counting',
      'Count and Circle',
      'Match Number to Quantity',
      'Ten-Frame Counting',
      'Missing Numbers',
      'More or Fewer?',
      'Cut and Paste the Numbers',
      'Number Star Certificate',
    ],
    helpsTitle: 'What These Number Activities Help Children Practise',
    helpsWith: [
      'Each number from 1 to 10 has a tracing and counting page that connects the written numeral, number word and a visible quantity. Pointing to one object at a time can help keep counting organised.',
      'Review pages introduce quantity matching, ten frames, missing numbers and comparisons using more or fewer. The final cut-and-paste activity asks children to count groups and match the correct numeral.',
    ],
    howToUse: [
      'Begin with a number the child is ready to explore rather than rushing through all ten.',
      'Point to each object while counting aloud, then ask how many there are altogether.',
      'Repeat the idea away from the page with blocks, buttons, snacks or other safe objects.',
      'Move to matching, missing-number and more-or-fewer pages after the quantities are familiar.',
    ],
    practicalTips: [
      'Use real objects so the child can touch and move one item for each number counted.',
      'Encourage careful one-to-one counting before focusing on speed.',
      'Supervise the final cut-and-paste activity and use child-safe scissors.',
    ],
    whoItsFor: 'Designed for parents and preschool teachers introducing number recognition, counting and quantities from 1 to 10 to children ages 3–5.',
    relatedFreebies: ['shapes-and-colours-activity-pack', 'pre-writing-pencil-control'],
    relatedLinks: [
      { label: 'Addition Level 1', href: '/games/math/addition-level-1', description: 'Continue with a free browser game for children ready to practise simple addition.' },
    ],
    seoTitle: 'Free Numbers 1–10 Activity Pack | Zalea Studio',
    seoDescription: 'Download 20 printable number activities for ages 3–5, with tracing, counting, quantity matching, ten frames and simple number comparisons.',
    notice: 'Grown-up supervision is required for the cut-and-paste page. Use child-safe scissors and provide help appropriate to the child’s experience.',
  },
  {
    slug: 'grade-tracker',
    title: 'Grade Tracker',
    shortTitle: 'Grade Tracker',
    description: 'Keep assignments, scores and final-grade goals organised in one simple set.',
    category: 'school-study',
    audience: 'Students',
    pageCount: 4,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/grade-tracker/Zalea_Studio_Grade_Tracker_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/grade-tracker/Zalea_Studio_Grade_Tracker_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/grade-tracker/Zalea_Studio_Grade_Tracker.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Grade Tracker', 'Assignment Tracker', 'Final Grade Planner'],
    helpsTitle: 'What This Tracker Helps With',
    helpsWith: [
      'Bring assignment names, returned scores and subject progress into one clear record instead of relying on separate notes or an online portal alone.',
      'The Final Grade Planner gives you a place to write down a target and think ahead before a major exam. It works well alongside Zalea’s grade tools when you want to calculate your current result or the score still needed.',
    ],
    howToUse: [
      'Keep a separate tracker for each subject so scores and deadlines remain easy to scan.',
      'Add assignments when they are set, then update the score after the work is returned.',
      'Review the Assignment Tracker each week and mark completed work as you go.',
      'Use the Final Grade Planner before an important exam to record your current position and target.',
    ],
    practicalTips: [
      'Choose one regular time each week to update every subject.',
      'Record scores exactly as they are returned so later calculations use consistent information.',
      'Keep the current sheet at the front of a subject folder or study binder.',
    ],
    whoItsFor: 'Designed for students who want a simple paper record of assignments, scores and final-grade goals. Teachers or families can also use it when helping a student review their workload.',
    relatedFreebies: ['study-planner'],
    relatedLinks: [
      { label: 'Grade Calculator', href: '/education/grade-calculator', description: 'Calculate an overall grade from assignment scores.' },
      { label: 'Final Grade Calculator', href: '/education/final-grade-calculator', description: 'Find the score needed on a final exam.' },
      { label: 'Weighted Grade Calculator', href: '/education/weighted-grade-calculator', description: 'Calculate a grade with weighted categories.' },
      { label: 'GPA Calculator', href: '/education/gpa-calculator', description: 'Estimate GPA from course grades and credits.' },
    ],
    seoTitle: 'Free Grade Tracker Printable | Zalea Studio',
    seoDescription: 'Organise assignments, scores and final-grade goals with a free Grade Tracker set for students, available in printable A4 and US Letter sizes.',
  },
  {
    slug: 'study-planner',
    title: 'Study Planner',
    shortTitle: 'Study Planner',
    description: 'Plan your week, focus each study session and prepare for exams.',
    category: 'school-study',
    audience: 'Students',
    pageCount: 4,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/study-planner/Zalea_Studio_Study_Planner_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/study-planner/Zalea_Studio_Study_Planner_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/study-planner/Zalea_Studio_Study_Planner.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Weekly Study Planner', 'Study Session Planner', 'Exam Revision Planner'],
    helpsTitle: 'What This Planner Helps With',
    helpsWith: [
      'Turn a busy week into smaller, visible study tasks. The weekly page provides the overview, while the session page helps you decide what one focused block of time should cover.',
      'The Exam Revision Planner is useful when several topics need attention before a test, helping you see what has been reviewed and what still needs time.',
    ],
    howToUse: [
      'Before the week starts, list the subjects, deadlines and revision tasks that need attention.',
      'Break broad goals such as “revise science” into specific topics or practice activities.',
      'Use the Study Session Planner to choose one clear focus, the materials needed and the next step.',
      'At the end of the week, move unfinished tasks forward instead of letting them disappear.',
    ],
    practicalTips: [
      'Leave some open space for work that appears during the week.',
      'Put the most time-sensitive exam topics first on the revision page.',
      'Keep each session realistic enough to finish in the time available.',
    ],
    whoItsFor: 'Made for students who prefer planning on paper and want separate pages for weekly organisation, individual study sessions and exam revision.',
    relatedFreebies: ['grade-tracker'],
    relatedLinks: [
      { label: 'Grade Calculator', href: '/education/grade-calculator', description: 'Keep track of your current overall grade.' },
      { label: 'Final Grade Calculator', href: '/education/final-grade-calculator', description: 'Plan the score you need on your final.' },
    ],
    seoTitle: 'Free Study Planner Printable | Zalea Studio',
    seoDescription: 'Plan weekly study tasks, focused sessions and exam revision with this Study Planner, available in printable A4 and US Letter sizes for students.',
  },
  {
    slug: 'student-progress-tracker',
    title: 'Student Progress Tracker',
    shortTitle: 'Student Progress Tracker',
    description: 'Track progress, celebrate strengths and see where extra support may be needed.',
    category: 'school-study',
    audience: 'Teachers, Tutors & Parents',
    pageCount: 4,
    format: 'A4 + US Letter • PDF',
    featured: false,
    published: true,
    a4Download: `${downloadRoot}/student-progress-tracker/Zalea_Studio_Student_Progress_Tracker_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/student-progress-tracker/Zalea_Studio_Student_Progress_Tracker_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/student-progress-tracker/Zalea_Studio_Student_Progress_Tracker.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Student Progress Overview', 'Assessment & Score Tracker', 'Learning Observation Notes'],
    helpsTitle: 'What This Tracker Helps Record',
    helpsWith: [
      'Keep educational notes in one place across lessons or tutoring sessions, including strengths, assessment results and areas where more practice may be helpful.',
      'The overview can show patterns over time, while the observation page leaves room for context that a score alone may not capture, such as strategies used or a topic that held the student’s interest.',
    ],
    howToUse: [
      'Start one set for each student and add the learning period or subject being observed.',
      'Record assessment scores with the date and enough context to understand what was measured.',
      'Write brief, factual observations after relevant lessons rather than trying to remember them later.',
      'Review earlier notes when planning the next practice activity or discussing progress with a family.',
    ],
    practicalTips: [
      'Describe what was observed instead of applying labels to the learner.',
      'Record strengths as well as areas that may need more support.',
      'Use dates consistently so changes can be viewed in sequence.',
    ],
    whoItsFor: 'Created for teachers, tutors and parents who need an informal educational record of scores, strengths and learning observations.',
    relatedFreebies: ['early-learning-skills-observation-tracker'],
    relatedLinks: [],
    seoTitle: 'Student Progress Tracker | Zalea Studio',
    seoDescription: 'Record strengths, assessment scores and learning observations with this student progress tracker for teachers, tutors and parents in two printable sizes.',
    notice: 'This is an informal educational record-keeping resource. It is not a medical, developmental or diagnostic tool.',
  },
  {
    slug: 'early-learning-skills-observation-tracker',
    title: 'Early Learning Skills & Observation Tracker',
    shortTitle: 'Early Learning Tracker',
    description: 'Keep track of growing skills, interests and next steps as learning happens.',
    category: 'school-study',
    audience: 'Teachers & Parents',
    ageRange: 'Ages 3–6',
    pageCount: 4,
    format: 'A4 + US Letter • PDF',
    featured: false,
    published: true,
    a4Download: `${downloadRoot}/early-learning-skills-observation-tracker/Zalea_Studio_Early_Learning_Skills_Observation_Tracker_A4.pdf`,
    usLetterDownload: `${downloadRoot}/early-learning-skills-observation-tracker/Zalea_Studio_Early_Learning_Skills_Observation_Tracker_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/early-learning-skills-observation-tracker/Zalea_Studio_Early_Learning_Skills_Observation_Tracker.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Early Learning Skills Overview', 'Learning Observation Notes', 'Interests, Strengths & Next Steps'],
    helpsTitle: 'What This Observation Tracker Helps With',
    helpsWith: [
      'Capture informal observations during play, routines and everyday learning. Notes can highlight emerging skills, interests and strengths without turning ordinary moments into formal testing.',
      'The final page helps adults connect an observation to a possible next activity—for example, offering more sorting play after a child shows interest in grouping objects.',
    ],
    howToUse: [
      'Observe during familiar activities and record what the child did in simple, factual language.',
      'Note interests and strengths alongside skills that are beginning to emerge.',
      'Add enough context to remember the activity, materials or support that was available.',
      'Choose a gentle next learning opportunity based on the child’s current interests and pace.',
    ],
    practicalTips: [
      'Use short notes from several moments instead of judging progress from one activity.',
      'Focus on what you can see and hear rather than making assumptions.',
      'Keep observations educational and share health or developmental concerns with an appropriate qualified professional.',
    ],
    whoItsFor: 'Designed for teachers and parents supporting children ages 3–6 through informal, everyday learning observations.',
    relatedFreebies: ['student-progress-tracker'],
    relatedLinks: [],
    seoTitle: 'Early Learning Observation Tracker | Zalea Studio',
    seoDescription: 'Record emerging skills, interests and learning observations for ages 3–6 with this informal tracker for teachers and parents in A4 and US Letter sizes.',
    notice: 'This is an informal educational observation tool, not a developmental screening or diagnostic assessment.',
  },
  {
    slug: 'pre-writing-pencil-control',
    title: 'Pre-Writing & Pencil Control',
    shortTitle: 'Pre-Writing & Pencil Control',
    longTitle: 'Pre-Writing & Pencil Control Starter Pack',
    description: 'Simple tracing activities to practise pencil control and early pre-writing skills.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 6,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/pre-writing-pencil-control/Zalea_Studio_Pre_Writing_Pencil_Control_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/pre-writing-pencil-control/Zalea_Studio_Pre_Writing_Pencil_Control_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/pre-writing-pencil-control/Zalea_Studio_Pre_Writing_Pencil_Control.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Straight Lines', 'Curves & Waves', 'Zigzags & Patterns', 'Shape Tracing', 'Follow the Path'],
    helpsTitle: 'What These Activities Help Children Practise',
    helpsWith: [
      'Offer a gentle progression from straight lines to curves, patterns, shapes and paths. Each page gives early learners a clear tracing activity without expecting perfect results.',
      'Short sessions can help children become familiar with moving a crayon, pencil or washable marker across the page at their own pace.',
    ],
    howToUse: [
      'Begin with the straight-line page before moving to curves, zigzags and shapes.',
      'Choose one page for a short session and stop when the child loses interest or becomes tired.',
      'Demonstrate the first movement if helpful, then allow the child to try independently.',
      'Repeat a favourite page later or place it in a reusable sleeve with a washable marker.',
    ],
    practicalTips: [
      'Use chunky crayons or pencils if they feel more comfortable for the child.',
      'Keep the paper steady and let the child choose a comfortable hand position.',
      'Encourage effort and exploration rather than neatness or perfection.',
    ],
    whoItsFor: 'Made for parents, preschool teachers and early learners ages 3–5 who want simple, low-pressure tracing practice.',
    relatedFreebies: ['fine-motor-activity-cards', 'scissor-skills-practice', 'first-phonics-activities'],
    relatedLinks: [],
    seoTitle: 'Pre-Writing & Pencil Control | Zalea Studio',
    seoDescription: 'Try simple line, pattern, shape and path tracing activities for ages 3–5, provided in printable A4 and US Letter sizes for home or preschool use.',
  },
  {
    slug: 'fine-motor-activity-cards',
    title: 'Fine Motor Activity Cards',
    shortTitle: 'Fine Motor Activity Cards',
    description: 'Choose from 48 playful activity ideas for strengthening little hands through everyday play.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 20,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/fine-motor-activity-cards/Zalea_Fine_Motor_Activity_Cards_48_Cards_A4.pdf`,
    usLetterDownload: `${downloadRoot}/fine-motor-activity-cards/Zalea_Fine_Motor_Activity_Cards_48_Cards_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/fine-motor-activity-cards/Zalea_Fine_Motor_Activity_Cards_48_Cards.zip`,
    bundleFormat: 'ZIP',
    includedPages: [
      'Cover',
      'Grown-Up Guide',
      'Simple Materials Guide',
      '48 Cut-Apart Activity Cards',
      'Pick 3 Today Planner',
      'Fine Motor Observation',
      'Favourite Activities',
      'Create Your Own Cards',
      'Fine Motor Star Certificate',
    ],
    helpsTitle: 'What These Activity Cards Help Children Practise',
    helpsWith: [
      'The 48 cards offer short activities using playdough, tongs, threading, paper, drawing materials and familiar household objects. Families can choose an idea that suits the materials and time available.',
      'Activities encourage hand strength, coordination and controlled movements through play. The supporting pages help adults note favourite activities and plan a small, manageable selection for one session.',
    ],
    howToUse: [
      'Read the grown-up guide and choose large, age-appropriate materials before beginning.',
      'Cut apart the cards, then invite the child to choose one or two activities.',
      'Demonstrate the movement when useful and allow plenty of time for the child to explore.',
      'Record favourites so enjoyable activities can be repeated on another day.',
    ],
    practicalTips: [
      'Use materials already available rather than trying to complete every card in order.',
      'Keep sessions short and finish while the activity is still enjoyable.',
      'Stay beside the child whenever an activity uses scissors, water, cords or small objects.',
    ],
    whoItsFor: 'Made for parents and preschool teachers looking for varied, low-pressure fine motor play ideas for children ages 3–5.',
    relatedFreebies: ['pre-writing-pencil-control', 'scissor-skills-practice'],
    relatedLinks: [],
    seoTitle: 'Free Fine Motor Activity Cards | Zalea Studio',
    seoDescription: 'Download 48 printable fine motor activity cards for ages 3–5, with playful ideas using playdough, tongs, threading, paper and everyday materials.',
    notice: 'Close adult supervision is required. Use child-safe scissors and large, age-appropriate materials, and consider choking, allergy and sensory needs before each activity.',
  },
  {
    slug: 'first-phonics-activities',
    title: 'First Phonics Activities',
    shortTitle: 'First Phonics Activities',
    description: 'Practise six early letter sounds, beginning sounds and simple blending through playful printable activities.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 20,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/first-phonics-activities/Zalea_First_Phonics_Activities_20_Pages_A4.pdf`,
    usLetterDownload: `${downloadRoot}/first-phonics-activities/Zalea_First_Phonics_Activities_20_Pages_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/first-phonics-activities/Zalea_First_Phonics_Activities_20_Pages.zip`,
    bundleFormat: 'ZIP',
    includedPages: [
      'Cover',
      'Before You Begin Guide',
      'Sounds s, a, t, p, i & n',
      'Beginning-Sound Matching',
      'Sound Sorting',
      'Choose the First Sound',
      'Sound Hunt',
      'Early Blending',
      'Read and Match',
      'Cut and Paste',
      'Phonics Sound Star Certificate',
    ],
    helpsTitle: 'What These Phonics Activities Help Children Practise',
    helpsWith: [
      'Introduce the sounds s, a, t, p, i and n through tracing, picture naming and beginning-sound matching. The sequence then moves toward sorting sounds and choosing the sound heard at the start of a word.',
      'Later pages provide a gentle introduction to blending short words such as at, sat, sit and pin. Adults can model each sound and revisit individual pages without treating the pack as a test.',
    ],
    howToUse: [
      'Read the short guidance page before introducing the first sound.',
      'Say the sound clearly, name the pictures together and let the child trace the letter.',
      'Move to matching and sorting after the individual sounds have become familiar.',
      'Use the blending pages slowly, pointing to each sound before sweeping across the word.',
    ],
    practicalTips: [
      'Practise one sound or one page at a time rather than completing the pack in one sitting.',
      'Say the sound cleanly without adding a strong extra vowel sound.',
      'Return to familiar sounds whenever a matching or blending activity feels difficult.',
    ],
    whoItsFor: 'Designed for parents and preschool teachers introducing early phonics practice to children ages 3–5.',
    relatedFreebies: ['pre-writing-pencil-control', 'fine-motor-activity-cards'],
    relatedLinks: [
      { label: 'English Games for Kids', href: '/english-games-for-kids', description: 'Explore more language-learning ideas and free browser activities.' },
    ],
    seoTitle: 'Free First Phonics Activities | Zalea Studio',
    seoDescription: 'Download 20 printable first phonics activity pages for ages 3–5, covering six letter sounds, beginning-sound matching and simple early blending.',
  },
  {
    slug: 'scissor-skills-practice',
    title: 'Scissor Skills Practice',
    shortTitle: 'Scissor Skills Practice',
    description: 'Build cutting confidence with simple snipping, line, shape and cut-and-paste activities for little hands.',
    category: 'kids-early-learning',
    audience: 'Parents, Preschool Teachers & Early Learners',
    ageRange: 'Ages 3–5',
    pageCount: 20,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/scissor-skills-practice/Zalea_Scissor_Skills_Practice_20_Pages_A4.pdf`,
    usLetterDownload: `${downloadRoot}/scissor-skills-practice/Zalea_Scissor_Skills_Practice_20_Pages_US_Letter.pdf`,
    bundleDownload: `${downloadRoot}/scissor-skills-practice/Zalea_Scissor_Skills_Practice_20_Pages.zip`,
    bundleFormat: 'ZIP',
    includedPages: [
      'Cover',
      'Before You Begin Guide',
      'Snipping Practice',
      'Straight, Zigzag, Curvy & Wavy Paths',
      'Shape Cutting',
      'Sorting and Matching',
      'Cut-and-Paste Pictures',
      'Loops, Spirals & Corners',
      'Fringe Cutting',
      'Scissor Skills Star Certificate',
    ],
    helpsTitle: 'What These Cutting Activities Help Children Practise',
    helpsWith: [
      'The activities begin with short snips and straight lines before introducing turns, curves, waves, shapes and simple cut-and-paste pictures. Children can work through the progression at a comfortable pace.',
      'Turning the paper, stopping at a marked point and following a path give children opportunities to coordinate both hands while using child-safe scissors with an adult nearby.',
    ],
    howToUse: [
      'Read the safety guidance and choose child-safe scissors that fit the child’s hand.',
      'Begin with the snipping page before trying longer straight paths.',
      'Introduce curves, corners and shapes gradually as confidence grows.',
      'Pause when hands become tired and repeat an easier page another day if needed.',
    ],
    practicalTips: [
      'Show the thumb-up hand position and demonstrate how the helper hand turns the paper.',
      'Print another copy of a favourite page when extra practice would be enjoyable.',
      'Praise careful handling and effort rather than expecting perfectly cut lines.',
    ],
    whoItsFor: 'Made for parents and preschool teachers supervising early cutting practice with children ages 3–5.',
    relatedFreebies: ['pre-writing-pencil-control', 'fine-motor-activity-cards'],
    relatedLinks: [],
    seoTitle: 'Free Scissor Skills Practice | Zalea Studio',
    seoDescription: 'Download 20 printable scissor skills pages for ages 3–5, progressing from simple snips and lines to shapes, turns and cut-and-paste activities.',
    notice: 'Grown-up supervision is required. Use child-safe scissors and teach children to keep blades pointed away from the body and to walk with scissors closed.',
  },
  {
    slug: 'savings-goal-tracker',
    title: 'Savings Goal Tracker',
    shortTitle: 'Savings Goal Tracker',
    description: 'Set a goal, track your progress and stay motivated along the way.',
    category: 'money-budgeting',
    audience: 'Anyone building a savings goal',
    pageCount: 2,
    format: 'A4 + US Letter • PDF',
    featured: true,
    published: true,
    a4Download: `${downloadRoot}/savings-goal-tracker/Zalea_Studio_Savings_Goal_Tracker_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/savings-goal-tracker/Zalea_Studio_Savings_Goal_Tracker_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/savings-goal-tracker/Zalea_Studio_Savings_Goal_Tracker.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Savings Goal Tracker'],
    helpsTitle: 'What This Savings Tracker Helps With',
    helpsWith: [
      'Focus on one savings goal, record the amount already available and make the remaining progress visible through smaller milestones.',
      'For example, if your goal is RM1,000 and you have already saved RM250, record RM750 as the amount left and divide the remainder into milestones that feel manageable.',
    ],
    howToUse: [
      'Choose one goal and write down its target amount and purpose.',
      'Record any money already saved so you have an accurate starting point.',
      'Break the amount left into smaller milestones and add a target date if that is useful.',
      'Update the savings log whenever money is added and review the amount remaining.',
    ],
    practicalTips: [
      'Keep the goal specific enough that progress is easy to recognise.',
      'Use milestones that suit your own income and timing rather than copying someone else’s plan.',
      'If circumstances change, revise the target or timeline instead of abandoning the tracker.',
    ],
    whoItsFor: 'Useful for anyone who wants a simple visual record while building one personal savings goal at a time.',
    relatedFreebies: ['big-purchase-planner', 'emergency-fund-planner'],
    relatedLinks: [
      { label: 'Savings Goal Calculator', href: '/finance/savings-goal-calculator', description: 'Estimate regular contributions for a savings target.' },
    ],
    seoTitle: 'Savings Goal Tracker | Zalea Studio',
    seoDescription: 'Set a savings goal, track milestones and record progress with this simple printable tracker in A4 and US Letter sizes for clear, motivating planning.',
    notice: 'This printable is for general educational and planning purposes and is not individualized financial advice.',
  },
  {
    slug: 'big-purchase-planner',
    title: 'Big Purchase Planner',
    shortTitle: 'Big Purchase Planner',
    description: 'Plan a major purchase with more clarity, intention and confidence.',
    category: 'money-budgeting',
    audience: 'Anyone planning a larger purchase',
    pageCount: 2,
    format: 'A4 + US Letter • PDF',
    featured: false,
    published: true,
    a4Download: `${downloadRoot}/big-purchase-planner/Zalea_Studio_Big_Purchase_Planner_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/big-purchase-planner/Zalea_Studio_Big_Purchase_Planner_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/big-purchase-planner/Zalea_Studio_Big_Purchase_Planner.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Big Purchase Planner'],
    helpsTitle: 'What This Purchase Planner Helps With',
    helpsWith: [
      'Slow down a larger purchase decision long enough to estimate the full cost, compare alternatives and decide whether the purchase is important now or can wait.',
      'It can be used for plans such as a laptop, furniture, travel or a phone, including related costs like delivery, warranty, maintenance or accessories where they apply.',
    ],
    howToUse: [
      'Describe the purchase and why it matters before looking only at price.',
      'Research a realistic total cost, including relevant ongoing or one-time extras.',
      'Compare a few alternatives and note the trade-offs that matter to you.',
      'Record how much is already available and divide the remaining amount across your intended timeline.',
    ],
    practicalTips: [
      'Compare like-for-like totals rather than headline prices alone.',
      'Leave room for price changes or costs that are not confirmed yet.',
      'Revisit the plan before committing to check whether the timing and priorities still make sense.',
    ],
    whoItsFor: 'For anyone who wants to think through and save toward a larger planned purchase without being told which product to buy.',
    relatedFreebies: ['savings-goal-tracker'],
    relatedLinks: [
      { label: 'Savings Goal Calculator', href: '/finance/savings-goal-calculator', description: 'Explore a contribution plan for the amount you want to save.' },
    ],
    seoTitle: 'Big Purchase Planner | Zalea Studio',
    seoDescription: 'Compare options, estimate total cost and plan savings for a larger purchase with this printable planner in A4 and US Letter sizes for thoughtful planning.',
    notice: 'This printable supports general planning and does not recommend a particular purchase or provide individualized financial advice.',
  },
  {
    slug: 'emergency-fund-planner',
    title: 'Emergency Fund Planner',
    shortTitle: 'Emergency Fund Planner',
    description: 'Build a buffer for the unexpected with a simple plan you can stick to.',
    category: 'money-budgeting',
    audience: 'Anyone building an emergency savings buffer',
    pageCount: 2,
    format: 'A4 + US Letter • PDF',
    featured: false,
    published: true,
    a4Download: `${downloadRoot}/emergency-fund-planner/Zalea_Studio_Emergency_Fund_Planner_A4_Final.pdf`,
    usLetterDownload: `${downloadRoot}/emergency-fund-planner/Zalea_Studio_Emergency_Fund_Planner_US_Letter_Final.pdf`,
    bundleDownload: `${downloadRoot}/emergency-fund-planner/Zalea_Studio_Emergency_Fund_Planner.zip`,
    bundleFormat: 'ZIP',
    includedPages: ['Cover', 'Emergency Fund Planner'],
    helpsTitle: 'What an Emergency Fund Plan Can Clarify',
    helpsWith: [
      'An emergency fund is money kept apart for unexpected essential expenses or a temporary disruption, rather than planned purchases or routine spending.',
      'Possible uses might include urgent home repairs, unexpected car repairs or a temporary income disruption. The planner helps you estimate essential monthly expenses and choose a personal target without treating one amount as correct for everyone.',
    ],
    howToUse: [
      'List essential monthly expenses using figures that reflect your own household.',
      'Choose an initial target that feels realistic for your circumstances and priorities.',
      'Record money already set aside, then calculate the gap between that amount and your target.',
      'Build gradually and review the plan when essential expenses or circumstances change.',
    ],
    practicalTips: [
      'Keep emergency savings distinct from money reserved for known bills or planned purchases.',
      'A smaller first milestone can make a larger long-term target easier to approach.',
      'Common ranges discussed elsewhere are general examples only; your target is a personal planning choice.',
    ],
    whoItsFor: 'For anyone who wants an educational worksheet to organise an emergency-savings target and track gradual progress.',
    relatedFreebies: ['savings-goal-tracker'],
    relatedLinks: [
      { label: 'Savings Goal Calculator', href: '/finance/savings-goal-calculator', description: 'Estimate contributions toward a personal savings target.' },
    ],
    seoTitle: 'Emergency Fund Planner | Zalea Studio',
    seoDescription: 'Estimate essential expenses, choose a personal target and track an emergency savings buffer with this printable planner in two sizes for gradual progress.',
    notice: 'This printable provides general educational planning information and is not individualized financial advice.',
  },
] as const;

export const publishedFreebies = freebies.filter((freebie) => freebie.published);

export const publishedCategoryKeys = (Object.keys(freebieCategories) as FreebieCategory[]).filter(
  (category) => publishedFreebies.some((freebie) => freebie.category === category),
);

export function getFreebie(slug: string) {
  return publishedFreebies.find((freebie) => freebie.slug === slug);
}
