import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BadgePercent, BarChart3, Calculator, ChartNoAxesCombined, Divide, Ratio } from 'lucide-react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const title = 'Free Math Calculators | Zalea Studio';
const description = 'Free online math calculators for percentages, fractions, ratios, averages and everyday calculations with clear formulas and step-by-step explanations.';

export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: '/math' }, openGraph: { title, description, url: '/math', type: 'website' } };

export default function MathToolsPage() {
  return <div className="min-h-screen bg-background"><SiteHeader /><main>
    <section className="border-b border-border/60 bg-gradient-to-b from-blue-50/70 to-background"><div className="mx-auto max-w-[1200px] px-4 py-16 text-center sm:px-6 lg:px-8 lg:py-24"><Badge variant="secondary" className="border-primary/20 bg-primary/10 text-primary">Free everyday calculations</Badge><h1 className="mx-auto mt-5 max-w-4xl text-balance text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Free Math Calculators</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Free online math calculators for percentages, fractions, ratios, averages and everyday calculations. Get instant answers with clear formulas and step-by-step explanations.</p></div></section>
    <section className="mx-auto max-w-[1200px] px-4 py-16 sm:px-6 lg:px-8 lg:py-24" aria-labelledby="math-calculators-heading"><div className="mb-10"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Choose a calculator</p><h2 id="math-calculators-heading" className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Available Math Tools</h2></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><MathToolCard href="/math/percentage-calculator" title="Percentage Calculator" description="Calculate percentages, percentage change, increases, decreases and reverse percentages with clear steps." icon={<BadgePercent className="h-6 w-6" aria-hidden="true" />} /><MathToolCard href="/math/fraction-calculator" title="Fraction Calculator" description="Add, subtract, multiply and divide fractions or mixed numbers with simplified answers and clear steps." icon={<Divide className="h-6 w-6" aria-hidden="true" />} /><MathToolCard href="/math/ratio-calculator" title="Ratio Calculator" description="Simplify ratios, find equivalent ratios and solve proportions or missing values with clear step-by-step results." icon={<Ratio className="h-6 w-6" aria-hidden="true" />} /><MathToolCard href="/math/average-calculator" title="Average Calculator" description="Calculate the average, median, mode, range, sum and more for any set of numbers." icon={<BarChart3 className="h-6 w-6" aria-hidden="true" />} /><MathToolCard href="/math/standard-deviation-calculator" title="Standard Deviation Calculator" description="Calculate sample and population standard deviation, variance and other key statistics with step-by-step results." icon={<ChartNoAxesCombined className="h-6 w-6" aria-hidden="true" />} /></div></section>
    <section className="border-y border-border/60 bg-secondary/30"><div className="mx-auto max-w-[1100px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Choose by problem</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Find the calculator that matches your numbers</h2><p className="mt-4 leading-relaxed text-muted-foreground">Each calculator focuses on a different relationship. Start by identifying whether you are comparing a part with a whole, working with fractions or ratios, or summarising a list of values.</p></div><div className="mt-8 grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Parts, totals and change</h3><p className="mt-3 leading-relaxed text-muted-foreground">Use the <Link href="/math/percentage-calculator" className="font-semibold text-primary hover:underline">Percentage Calculator</Link> for a percentage of a number, percentage change, increases, decreases or reverse percentages.</p></div><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Fractions and proportions</h3><p className="mt-3 leading-relaxed text-muted-foreground">The <Link href="/math/fraction-calculator" className="font-semibold text-primary hover:underline">Fraction Calculator</Link> handles fraction arithmetic and mixed numbers. Choose the <Link href="/math/ratio-calculator" className="font-semibold text-primary hover:underline">Ratio Calculator</Link> to simplify ratios, scale them, or solve a missing value.</p></div><div className="rounded-2xl border border-border/70 bg-white p-6"><h3 className="text-xl font-bold">Describe a data set</h3><p className="mt-3 leading-relaxed text-muted-foreground">Use the <Link href="/math/average-calculator" className="font-semibold text-primary hover:underline">Average Calculator</Link> for mean, median, mode and range. Use the <Link href="/math/standard-deviation-calculator" className="font-semibold text-primary hover:underline">Standard Deviation Calculator</Link> when you also need variance and spread.</p></div></div></div></section>
    <section className="mx-auto max-w-[1000px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">How to check a result</h2><p className="mt-4 leading-relaxed text-muted-foreground">Enter values in the form requested, paying attention to negative signs, decimal points and whether a field expects a percentage or an ordinary number. After calculating, compare the displayed formula and intermediate steps with the original problem.</p><p className="mt-4 leading-relaxed text-muted-foreground">For statistics, decide whether the values represent an entire population or a sample. For ratios and fractions, keep quantities in compatible units before comparing or simplifying them.</p></div><aside className="rounded-2xl border border-blue-200 bg-blue-50/60 p-6 sm:p-8" aria-labelledby="math-rounding-note"><h2 id="math-rounding-note" className="text-2xl font-bold">Rounding and interpretation</h2><p className="mt-4 leading-relaxed text-muted-foreground">A displayed decimal may be rounded for readability even when the calculator uses a more precise value internally. If the result will be used in schoolwork, finance, measurement or another formal setting, follow the rounding method and notation required for that context.</p></aside></div></section>
    <section className="border-t border-border/60 bg-secondary/30"><div className="mx-auto max-w-3xl px-4 py-16 text-center sm:px-6 lg:px-8 lg:py-20"><Calculator className="mx-auto h-10 w-10 text-primary" aria-hidden="true" /><h2 className="mt-4 text-3xl font-bold tracking-tight">Math made clearer</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">Math Tools are designed for quick everyday calculations without accounts or external services. Each result includes the formula used so you can understand the answer as well as calculate it.</p></div></section>
  </main><SiteFooter /></div>;
}

function MathToolCard({ href, title, description, icon }: { href: string; title: string; description: string; icon: React.ReactNode }) {
  return <Link href={href} className="group rounded-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><Card className="h-full border-border/60 shadow-sm transition-all group-hover:-translate-y-1 group-hover:shadow-md"><CardHeader><span className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><CardTitle className="flex items-center justify-between gap-3 text-xl">{title}<ArrowRight className="h-5 w-5 shrink-0 text-primary transition-transform group-hover:translate-x-1" aria-hidden="true" /></CardTitle></CardHeader><CardContent><p className="leading-relaxed text-muted-foreground">{description}</p></CardContent></Card></Link>;
}

