import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, CircleHelp, School } from 'lucide-react';
import { GpaCalculator } from '@/components/education/gpa-calculator';
import { RelatedEducationTools } from '@/components/education/related-education-tools';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { gpaScale } from '@/lib/gpa';
import { safeJsonLd } from '@/lib/seo';
import { SITE_URL } from '@/lib/site';

const title = 'GPA Calculator – Calculate Your GPA on a 4.0 Scale | Zalea Studio';
const description = 'Calculate semester or cumulative GPA from letter grades, plus/minus grades and credit hours using a clearly documented 4.0 reference scale.';
const path = '/education/gpa-calculator';
export const metadata: Metadata = { title: { absolute: title }, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: 'website' } };

const faqs = [
  { question: 'How do I calculate GPA on a 4.0 scale?', answer: 'Multiply each course grade point by its credit hours, add all quality points, then divide by the total credit hours.' },
  { question: "What is my GPA if I earn all A's?", answer: 'On this calculator’s unweighted scale, A+ and A both equal 4.0. If every included course has either grade, the result is 4.0 regardless of differing credit hours.' },
  { question: 'How are plus and minus grades calculated?', answer: 'This reference scale uses A− = 3.7, B+ = 3.3, B− = 2.7, C+ = 2.3, C− = 1.7, D+ = 1.3 and D− = 0.7. The full mapping appears below.' },
  { question: 'Can I enter numeric or percentage grades?', answer: 'No. This calculator accepts letter grades and credit hours. Convert a numeric grade using your institution’s official grading thresholds before selecting a letter grade.' },
  { question: 'What is a 90% grade on a 4.0 scale?', answer: 'There is no universal answer. One institution may classify 90% as an A worth 4.0, while another may use different thresholds or grade points.' },
  { question: 'Can a GPA be higher than 4.0?', answer: 'Yes, in some weighted systems where advanced courses receive extra grade points. This calculator is unweighted and caps both A+ and A at 4.0.' },
  { question: 'What is the difference between weighted and unweighted GPA?', answer: 'An unweighted GPA normally caps grades at 4.0. A weighted system may award extra points for advanced courses and can produce results above 4.0.' },
  { question: 'Do all schools use the same GPA scale?', answer: 'No. Letter mappings, percentage thresholds, course weighting and maximum GPA can vary. Check your school or university’s official policy.' },
];
const jsonLd = [
  { '@context': 'https://schema.org', '@type': 'WebApplication', name: 'GPA Calculator', url: `${SITE_URL}${path}`, description, applicationCategory: 'EducationalApplication', operatingSystem: 'Any', browserRequirements: 'Requires a modern web browser with JavaScript enabled.', isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } },
  { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Education', item: `${SITE_URL}/education` }, { '@type': 'ListItem', position: 3, name: 'GPA Calculator', item: `${SITE_URL}${path}` }] },
  { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) },
];
const guides = [
  { title: 'How to Calculate GPA on a 4.0 Scale', body: <><p><strong>GPA = total quality points ÷ total credit hours.</strong> Quality points equal grade points × credit hours.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[400px] text-left text-sm"><thead><tr className="border-b border-border"><th className="py-2 pr-3">Course</th><th className="py-2 pr-3">Grade</th><th className="py-2 pr-3">Points</th><th className="py-2 pr-3">Credits</th><th className="py-2">Quality points</th></tr></thead><tbody><tr><td className="py-2 pr-3">Course A</td><td className="py-2 pr-3">A</td><td className="py-2 pr-3">4.0</td><td className="py-2 pr-3">3</td><td className="py-2">12.0</td></tr><tr><td className="py-2 pr-3">Course B</td><td className="py-2 pr-3">B+</td><td className="py-2 pr-3">3.3</td><td className="py-2 pr-3">3</td><td className="py-2">9.9</td></tr></tbody></table></div><p className="mt-3">21.9 quality points ÷ 6 credits = <strong>3.65 GPA</strong>.</p></> },
  { title: 'Understanding This 4.0 Scale', body: <p>A 4.0 scale assigns grade points to letter grades. This calculator uses A+ and A = 4.0 and includes plus/minus grades down to D− = 0.7. It is an unweighted reference scale, not a universal policy; institutions may use different mappings.</p> },
  { title: 'Percentage and Numeric Grades', body: <p>This calculator does not apply a universal percentage-to-GPA formula. A score such as 90%, 94% or 78% must first be interpreted using the institution’s official letter-grade thresholds, which can differ between schools.</p> },
  { title: 'GPA Above 4.0', body: <p>A GPA such as 4.27 usually comes from a weighted system that awards extra points for advanced courses. It should not be converted proportionally to an unweighted 4.0 scale. This calculator’s results do not exceed 4.0.</p> },
  { title: 'How to Calculate Cumulative GPA', body: <p><strong>Cumulative GPA = total quality points across all semesters ÷ total completed credits.</strong> The calculator can combine a previous GPA and credit total with the current or a manually entered semester.</p> },
  { title: 'Related Grade Tools', body: <p>This GPA calculator uses course letter grades and credits. Use the <Link href="/education/grade-calculator" className="font-semibold text-primary hover:underline">Grade Calculator</Link> for points earned, or the <Link href="/education/weighted-grade-calculator" className="font-semibold text-primary hover:underline">Weighted Grade Calculator</Link> for assignment and category percentages.</p> },
];

export default function GpaCalculatorPage() {
  return <div className="min-h-screen bg-background"><SiteHeader /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(jsonLd) }} />
    <section className="border-b border-border/60 bg-gradient-to-b from-blue-50/70 to-background"><div className="mx-auto max-w-[1200px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><Link href="/" className="hover:text-foreground hover:underline">Home</Link><span aria-hidden="true">/</span><Link href="/education" className="hover:text-foreground hover:underline">Education</Link><span aria-hidden="true">/</span><span aria-current="page">GPA Calculator</span></nav><Link href="/education" className="inline-flex items-center text-sm font-medium text-primary hover:underline"><ArrowLeft className="mr-2 h-4 w-4" aria-hidden="true" />All Education Tools</Link><Badge variant="secondary" className="mt-6 block w-fit border-primary/20 bg-primary/10 text-primary">Free calculator</Badge><h1 className="mt-4 max-w-4xl text-balance text-4xl font-bold tracking-tight sm:text-5xl">GPA Calculator</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-muted-foreground">Estimate semester or cumulative GPA on an unweighted 4.0 reference scale. Enter course letter grades—including plus/minus grades—and credit hours. Numeric and percentage grades are not entered directly.</p></div></section>
    <section className="mx-auto max-w-[1200px] px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><GpaCalculator /></section>
    <section className="border-y border-border/60 bg-secondary/30"><div className="mx-auto grid max-w-[1000px] gap-6 px-4 py-14 sm:px-6 md:grid-cols-2 lg:px-8 lg:py-20">{guides.map((guide) => <Card key={guide.title} className="min-w-0 border-border/60 shadow-sm"><CardHeader><span className="mb-2 flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><School className="h-6 w-6" aria-hidden="true" /></span><CardTitle className="text-xl">{guide.title}</CardTitle></CardHeader><CardContent className="min-w-0 leading-relaxed text-muted-foreground">{guide.body}</CardContent></Card>)}</div></section>
    <section className="mx-auto max-w-[800px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20" aria-labelledby="gpa-scale-heading"><div className="text-center"><School className="mx-auto h-9 w-9 text-primary" aria-hidden="true" /><h2 id="gpa-scale-heading" className="mt-4 text-3xl font-bold tracking-tight">GPA Scale Reference</h2></div><div className="mx-auto mt-8 max-w-xl overflow-hidden rounded-2xl border border-border/60 bg-card shadow-sm"><table className="w-full text-left"><thead className="bg-secondary"><tr><th scope="col" className="px-5 py-3 font-semibold">Letter Grade</th><th scope="col" className="px-5 py-3 font-semibold">Grade Point</th></tr></thead><tbody className="divide-y divide-border">{gpaScale.map(([letter, point]) => <tr key={letter}><td className="px-5 py-3 font-semibold">{letter}</td><td className="px-5 py-3">{point.toFixed(1)}</td></tr>)}</tbody></table></div><p className="mx-auto mt-5 max-w-2xl rounded-xl bg-secondary/50 p-4 text-sm leading-relaxed text-muted-foreground">Your institution may use a different grading scale. Always check your official school or university grading policy.</p></section>
    <section className="mx-auto max-w-[800px] px-4 py-14 sm:px-6 lg:px-8 lg:py-20" aria-labelledby="gpa-faq"><div className="text-center"><CircleHelp className="mx-auto h-9 w-9 text-primary" aria-hidden="true" /><h2 id="gpa-faq" className="mt-4 text-3xl font-bold tracking-tight">Frequently Asked Questions</h2></div><div className="mt-9 divide-y divide-border rounded-2xl border border-border/60 bg-card px-6 shadow-sm">{faqs.map((faq) => <div key={faq.question} className="py-6"><h3 className="font-semibold">{faq.question}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{faq.answer}</p></div>)}</div></section>
    <div className="border-t border-border/60"><RelatedEducationTools currentSlug="gpa-calculator" /></div>
  </main><SiteFooter /></div>;
}
