import type { Metadata } from 'next';
import { GuidePage } from '@/components/guides/guide-page';

const path = '/guides/pre-writing-skills-activities';
const title = 'Pre-Writing Skills and Activities for Young Children';
const description = 'Practical, low-pressure activities that support early mark-making, hand control and familiarity with the movements used in writing.';
export const metadata: Metadata = { title: { absolute: `${title} | Zalea Studio` }, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: 'article' }, twitter: { card: 'summary', title, description } };

export default function PreWritingGuidePage() {
  return <GuidePage title={title} description={description} path={path} eyebrow="Parent and teacher guide" relatedLinks={[
    { label: 'Pre-Writing & Pencil Control', href: '/freebies/pre-writing-pencil-control', description: 'Download simple line, pattern, shape and path tracing pages.' },
    { label: 'Fine Motor Activity Cards', href: '/freebies/fine-motor-activity-cards', description: 'Choose from playful hand-strength and coordination ideas using everyday materials.' },
    { label: 'Scissor Skills Practice', href: '/freebies/scissor-skills-practice', description: 'Try supervised snipping, line, shape and cut-and-paste activities.' },
  ]}>
    <section><h2 className="text-3xl font-bold tracking-tight">Pre-writing begins before letter worksheets</h2><p className="mt-4 leading-7 text-muted-foreground">Before forming letters, children experiment with marks and learn to guide their eyes and hands together. Drawing a road for a toy car, making dots in dough, following a curved path and turning a page all provide useful experiences. The aim is comfortable control and purposeful movement—not perfect handwriting at an early age.</p><p className="mt-4 leading-7 text-muted-foreground">Activities can develop several related skills: using both hands together, adjusting pressure, moving across a page, stopping at a point and noticing simple lines and shapes. Children build these skills at different rates, so choose tasks that feel achievable and enjoyable rather than treating a page as a test.</p></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Useful movement patterns</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Activity title="Vertical and horizontal lines">Draw rain falling, roads crossing a page or fences made from craft sticks.</Activity><Activity title="Curves and circles">Trace around lids, make loops in sand or draw bubbles of different sizes.</Activity><Activity title="Zigzags and changes of direction">Follow mountain paths, connect matching pictures or guide a toy around corners.</Activity><Activity title="Start-and-stop control">Place dots to join, move small objects into marked spaces or draw short lines between two points.</Activity></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Simple activities without worksheets</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Use tongs to move large, age-appropriate objects between bowls.</li><li>Roll, pinch and press playdough, then make tracks through it with a finger.</li><li>Draw large shapes with chalk, water and a brush, or a finger in a shallow tray of sand.</li><li>Thread large pieces, build with blocks, peel reusable stickers or tear paper for a collage.</li><li>Place paper on a vertical surface so the child can make broad marks while standing.</li></ul><p className="mt-4 leading-7 text-muted-foreground">Choose materials appropriate for the child and supervise activities involving small objects, cords, water or tools. Large movements are often easier before smaller pencil movements.</p></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">A short practice sequence</h2><ol className="mt-6 space-y-5"><Step number="1" title="Warm up through play">Spend a few minutes squeezing dough, moving objects with tongs or drawing large shapes.</Step><Step number="2" title="Model one movement">Show where a line begins and move slowly in the intended direction.</Step><Step number="3" title="Offer a small amount">Try one pattern or part of a page, then pause while the experience is still positive.</Step><Step number="4" title="Use the movement elsewhere">Repeat it with chalk, paint, a finger in sand or a path for a toy.</Step></ol></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">Helpful adult support</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Offer chunky crayons, pencils or chalk when they are easier to control.</li><li>Keep the page steady but allow a comfortable hand choice and position.</li><li>Describe the movement—“down, across, stop”—instead of commenting only on neatness.</li><li>Repeat a favourite activity rather than racing through every available page.</li></ul></div><div><h2 className="text-3xl font-bold tracking-tight">Common sources of pressure</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Expecting small, precise shapes before broad movements feel easy.</li><li>Correcting every mark instead of noticing effort and purposeful control.</li><li>Continuing after the child&apos;s hand is tired or attention has moved on.</li><li>Comparing one child&apos;s page with another child&apos;s work.</li></ul></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">From paths to meaningful marks</h2><p className="mt-4 leading-7 text-muted-foreground">When lines and shapes become familiar, invite the child to use them in pictures: circles for faces, lines for legs, crosses for windows or waves for water. Later, point out similar movements within letters without requiring formal practice every time. Drawing and talking about the picture gives marks a purpose and keeps early writing connected to communication.</p><p className="mt-4 leading-7 text-muted-foreground">These activities are general educational ideas, not developmental assessment. If you have concerns about a child&apos;s movement, vision, pain or development, discuss them with an appropriately qualified professional.</p></section>
  </GuidePage>;
}

function Activity({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-border/60 bg-card p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{children}</p></div>; }
function Step({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <li className="flex gap-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">{number}</span><div><h3 className="font-bold">{title}</h3><p className="mt-1 leading-7 text-muted-foreground">{children}</p></div></li>; }
