import type { Metadata } from 'next';
import { GuidePage } from '@/components/guides/guide-page';

const path = '/guides/percentage-points-vs-percentage-change';
const title = 'Percentage Points vs Percentage Change';
const description = 'Learn how percentage points differ from percentage increase or decrease, with clear formulas and everyday examples.';
export const metadata: Metadata = { title: { absolute: `${title} | Zalea Studio` }, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: 'article' }, twitter: { card: 'summary', title, description } };

export default function PercentagePointsGuidePage() {
  return <GuidePage title={title} description={description} path={path} eyebrow="Math in context guide" relatedLinks={[
    { label: 'Percentage Calculator', href: '/math/percentage-calculator', description: 'Calculate percentages, percentage change and reverse percentages.' },
    { label: 'Discount Calculator', href: '/finance/discount-calculator', description: 'Turn an advertised discount rate into a saving and final price.' },
    { label: 'Cashback Calculator', href: '/finance/cashback-calculator', description: 'Apply a cashback percentage and optional reward cap.' },
  ]}>
    <section><h2 className="text-3xl font-bold tracking-tight">The short distinction</h2><p className="mt-4 leading-7 text-muted-foreground"><strong className="text-foreground">Percentage points</strong> describe the simple difference between two percentages. <strong className="text-foreground">Percentage change</strong> describes that difference relative to the starting percentage. They answer different questions, so both numbers can be correct.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><Formula title="Percentage-point difference">New percentage − original percentage</Formula><Formula title="Percentage change">(New − original) ÷ original × 100</Formula></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Worked example: a rate rises from 20% to 25%</h2><p className="mt-4 leading-7 text-muted-foreground">The percentage-point increase is 25% − 20% = <strong>5 percentage points</strong>. To measure the increase relative to the original 20%, divide the 5-point difference by 20: 5 ÷ 20 × 100 = <strong>25% increase</strong>.</p><p className="mt-4 leading-7 text-muted-foreground">Saying the rate “rose by 5%” is ambiguous and, if interpreted as relative change, incorrect. A 5% increase on 20% would produce 21%, because 20% × 1.05 = 21%.</p></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Why the starting rate matters</h2><p className="mt-4 leading-7 text-muted-foreground">A movement of 5 percentage points is a much larger relative change when the original rate is small. Moving from 5% to 10% is a 5-point increase but a 100% relative increase. Moving from 80% to 85% is also a 5-point increase, yet the relative increase is only 6.25%.</p><div className="mt-6 overflow-x-auto rounded-2xl border border-border/60"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-secondary/60"><tr><th className="p-4">Change</th><th className="p-4">Points</th><th className="p-4">Relative change</th></tr></thead><tbody className="divide-y divide-border"><tr><td className="p-4">5% → 10%</td><td className="p-4">+5 points</td><td className="p-4">+100%</td></tr><tr><td className="p-4">20% → 25%</td><td className="p-4">+5 points</td><td className="p-4">+25%</td></tr><tr><td className="p-4">80% → 85%</td><td className="p-4">+5 points</td><td className="p-4">+6.25%</td></tr></tbody></table></div></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">When to use each term</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Use percentage points when comparing rates, shares or proportions stated as percentages.</li><li>Use percentage change when the question asks how large the movement is relative to its starting value.</li><li>State both when readers could reasonably want either interpretation.</li></ul></div><div><h2 className="text-3xl font-bold tracking-tight">Common mistakes</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Putting a percent sign after a simple subtraction and omitting “percentage points.”</li><li>Dividing by the new rate instead of the original rate for percentage change.</li><li>Using relative change when the starting value is zero; division by zero makes that comparison undefined.</li><li>Assuming a percentage increase and decrease of the same size cancel each other.</li></ul></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">A practical wording check</h2><p className="mt-4 leading-7 text-muted-foreground">When you read that a rate “increased by 10%,” look for the starting and ending values. If it moved from 30% to 40%, the increase is 10 percentage points and about 33.3% relative to the starting rate. Clear reporting should say which measure is intended.</p></section>
  </GuidePage>;
}

function Formula({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-primary/20 bg-primary/5 p-6"><h3 className="font-bold">{title}</h3><p className="mt-3 font-mono text-sm text-foreground/80">{children}</p></div>; }
