import type { Metadata } from 'next';
import Link from 'next/link';
import { GuidePage } from '@/components/guides/guide-page';

const path = '/guides/how-to-set-a-realistic-savings-goal';
const title = 'How to Set a Realistic Savings Goal';
const description = 'Choose a clear savings target, test a manageable monthly contribution and adjust the plan when real life changes.';
export const metadata: Metadata = { title: { absolute: `${title} | Zalea Studio` }, description, alternates: { canonical: path }, openGraph: { title, description, url: path, type: 'article' }, twitter: { card: 'summary', title, description } };

export default function SavingsGoalGuidePage() {
  return <GuidePage title={title} description={description} path={path} eyebrow="Money planning guide" relatedLinks={[
    { label: 'Savings Goal Calculator', href: '/finance/savings-goal-calculator', description: 'Estimate the contribution months after choosing a target and realistic monthly amount.' },
    { label: 'Savings Goal Tracker', href: '/freebies/savings-goal-tracker', description: 'Record milestones and actual progress with a free printable.' },
    { label: 'Big Purchase Planner', href: '/freebies/big-purchase-planner', description: 'Think through the full cost and alternatives for a planned purchase.' },
  ]}>
    <section><h2 className="text-3xl font-bold tracking-tight">Start with the reason, not a round number</h2><p className="mt-4 leading-7 text-muted-foreground">A useful savings goal identifies what the money is for, how much is needed and roughly when it may be needed. “Save more” gives no finish line. “Set aside RM1,800 for course fees due next March” can be checked, divided into contributions and revised if the fee or timing changes.</p><p className="mt-4 leading-7 text-muted-foreground">Before choosing the amount, list the costs that belong to the goal. A trip might include transport, accommodation, insurance and local travel. A laptop goal may need an adapter, delivery or software. This avoids reaching a headline price and discovering that the usable total is higher.</p></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Separate three parts of the plan</h2><div className="mt-6 grid gap-5 sm:grid-cols-3"><GuideBox title="Target">The estimated total cost, including relevant extras and a modest allowance for uncertain costs.</GuideBox><GuideBox title="Starting amount">Money already reserved for this purpose—not the entire balance of an account used for other needs.</GuideBox><GuideBox title="Contribution">An amount that can usually be set aside without relying on a perfect month.</GuideBox></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Worked example: course fees</h2><p className="mt-4 leading-7 text-muted-foreground">Suppose a course and required materials are expected to cost RM2,400. You already have RM600 reserved, leaving RM1,800. Saving RM300 each month would take six monthly contributions. Saving RM225 would take eight.</p><div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-6"><p className="font-semibold">Remaining amount = RM2,400 − RM600 = RM1,800</p><p className="mt-2 font-semibold">Months at RM300 = RM1,800 ÷ RM300 = 6</p></div><p className="mt-4 leading-7 text-muted-foreground">The faster plan is not automatically better. If RM300 makes ordinary bills difficult, the eight-month plan may be more sustainable, or the target date may need to move. Use the <Link href="/finance/savings-goal-calculator" className="font-semibold text-primary hover:underline">Savings Goal Calculator</Link> to compare both contribution amounts rather than treating the first answer as a commitment.</p></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight">Check whether it is realistic</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Base the contribution on ordinary income and expenses, not the best month of the year.</li><li>Keep known bills and emergency money distinct from funds assigned to the goal.</li><li>Leave some flexibility for irregular costs so one surprise does not end the plan.</li><li>Check whether the target date is a true deadline or simply a preference.</li></ul></div><div><h2 className="text-3xl font-bold tracking-tight">Common planning mistakes</h2><ul className="mt-5 list-disc space-y-3 pl-5 leading-7 text-muted-foreground"><li>Counting the same starting savings toward several goals.</li><li>Ignoring additional or changing costs until the final month.</li><li>Setting a contribution from leftover money without deciding when it will be transferred.</li><li>Abandoning the goal after one missed month instead of recalculating.</li></ul></div></section>
    <section className="mt-12"><h2 className="text-3xl font-bold tracking-tight">Review the plan without moving the finish line casually</h2><p className="mt-4 leading-7 text-muted-foreground">A monthly check can compare planned and actual contributions. If the gap is temporary, keep the target and update the expected date. If the underlying cost or income has changed, revise the target, contribution or timing explicitly. Recording why the plan changed helps distinguish a considered adjustment from repeatedly borrowing from the goal.</p><p className="mt-4 leading-7 text-muted-foreground">This guide and calculator provide general planning examples, not personalised financial advice. The right priority and buffer depend on your own obligations and circumstances.</p></section>
  </GuidePage>;
}

function GuideBox({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-border/60 bg-card p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{children}</p></div>; }
