'use client';

import { useMemo, useRef, useState } from 'react';
import { Plus, RotateCcw, School, Sparkles, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { calculateCumulativeGpa, calculateSemesterGpa, gpaScale, gradePointsFor, type GpaLetter, type SemesterGpaResult } from '@/lib/gpa';

type Mode = 'semester' | 'cumulative';
type Source = 'current' | 'manual';
type CourseRow = { id: number; name: string; grade: GpaLetter | ''; credits: string };
const maximumCredits = 1_000_000;
const blankCourses = (): CourseRow[] => [1, 2, 3, 4].map((id) => ({ id, name: `Course ${id}`, grade: '', credits: '' }));
const exampleCourses: CourseRow[] = [
  { id: 1, name: 'Mathematics', grade: 'A', credits: '3' }, { id: 2, name: 'English', grade: 'B+', credits: '3' },
  { id: 3, name: 'Science', grade: 'A−', credits: '4' }, { id: 4, name: 'History', grade: 'B', credits: '3' },
];

export function GpaCalculator() {
  const [mode, setMode] = useState<Mode>('semester');
  const [courses, setCourses] = useState<CourseRow[]>(blankCourses);
  const [source, setSource] = useState<Source>('current');
  const [previousGpa, setPreviousGpa] = useState('3.20');
  const [previousCredits, setPreviousCredits] = useState('60');
  const [manualGpa, setManualGpa] = useState('3.52');
  const [manualCredits, setManualCredits] = useState('13');
  const nextId = useRef(5);

  const semesterState = useMemo(() => {
    const entered = courses.filter((course) => course.grade !== '' || course.credits.trim() !== '');
    if (entered.length === 0) return { result: null, error: null };
    for (const course of entered) { const error = validateCourse(course); if (error) return { result: null, error: `${course.name.trim() || 'Untitled course'}: ${error}` }; }
    return { result: calculateSemesterGpa(entered.map((course) => ({ grade: course.grade as GpaLetter, credits: Number(course.credits) }))), error: null };
  }, [courses]);

  const cumulativeState = useMemo(() => {
    const baseError = validateCumulativeBase(previousGpa, previousCredits);
    if (baseError) return { result: null, error: baseError, newGpa: null, newCredits: null };
    const newGpa = source === 'current' ? semesterState.result?.gpa ?? null : Number(manualGpa);
    const newCredits = source === 'current' ? semesterState.result?.totalCredits ?? null : Number(manualCredits);
    if (source === 'current' && (!semesterState.result || semesterState.error)) return { result: null, error: 'Enter valid semester courses or choose manual semester values.', newGpa: null, newCredits: null };
    if (source === 'manual') { const error = validateManualSemester(manualGpa, manualCredits); if (error) return { result: null, error, newGpa: null, newCredits: null }; }
    return { result: calculateCumulativeGpa(Number(previousGpa), Number(previousCredits), newGpa as number, newCredits as number), error: null, newGpa, newCredits };
  }, [manualCredits, manualGpa, previousCredits, previousGpa, semesterState.error, semesterState.result, source]);

  const updateCourse = (id: number, field: keyof Omit<CourseRow, 'id'>, value: string) => setCourses((current) => current.map((course) => course.id === id ? { ...course, [field]: value } as CourseRow : course));
  const addCourse = () => { const id = nextId.current++; setCourses((current) => [...current, { id, name: `Course ${current.length + 1}`, grade: '', credits: '' }]); };
  const removeCourse = (id: number) => setCourses((current) => current.length === 1 ? current : current.filter((course) => course.id !== id));
  const loadExample = () => { setCourses(exampleCourses.map((course) => ({ ...course }))); setPreviousGpa('3.20'); setPreviousCredits('60'); setManualGpa('3.52'); setManualCredits('13'); setSource('current'); nextId.current = 5; };
  const reset = () => { setCourses(blankCourses()); setPreviousGpa(''); setPreviousCredits(''); setManualGpa(''); setManualCredits(''); setSource('current'); nextId.current = 5; };

  return <Card className="overflow-hidden border-border/60 shadow-lg"><CardHeader className="border-b border-border/60 bg-card"><CardTitle className="flex items-center gap-2 text-2xl"><School className="h-6 w-6 text-primary" aria-hidden="true" />Calculate your GPA</CardTitle><p className="mt-2 text-sm text-muted-foreground">Uses a common 4.0 scale with A+ and A both equal to 4.0. Values stay in your browser.</p></CardHeader><CardContent className="p-4 sm:p-6"><div role="tablist" aria-label="GPA calculator mode" className="grid grid-cols-2 gap-1 rounded-xl bg-secondary p-1"><ModeTab selected={mode === 'semester'} onClick={() => setMode('semester')}>Semester GPA</ModeTab><ModeTab selected={mode === 'cumulative'} onClick={() => setMode('cumulative')}>Cumulative GPA</ModeTab></div>
    {mode === 'semester' ? <SemesterPanel courses={courses} result={semesterState.result} error={semesterState.error} updateCourse={updateCourse} addCourse={addCourse} removeCourse={removeCourse} loadExample={loadExample} reset={reset} /> : <CumulativePanel source={source} setSource={setSource} previousGpa={previousGpa} setPreviousGpa={setPreviousGpa} previousCredits={previousCredits} setPreviousCredits={setPreviousCredits} manualGpa={manualGpa} setManualGpa={setManualGpa} manualCredits={manualCredits} setManualCredits={setManualCredits} semester={semesterState.result} resultState={cumulativeState} loadExample={loadExample} reset={reset} />}
  </CardContent></Card>;
}

function SemesterPanel({ courses, result, error, updateCourse, addCourse, removeCourse, loadExample, reset }: { courses: CourseRow[]; result: SemesterGpaResult | null; error: string | null; updateCourse: (id: number, field: keyof Omit<CourseRow, 'id'>, value: string) => void; addCourse: () => void; removeCourse: (id: number) => void; loadExample: () => void; reset: () => void }) {
  return <div role="tabpanel" className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><section aria-label="Semester courses"><div className="hidden grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)_minmax(0,0.8fr)_minmax(0,0.8fr)_minmax(5rem,0.9fr)_3rem] gap-3 px-3 pb-2 text-sm font-semibold text-muted-foreground md:grid" aria-hidden="true"><span>Course Name</span><span>Letter Grade</span><span>Credit Hours</span><span>Grade Points</span><span>Quality Points</span><span>Remove</span></div><div className="space-y-3">{courses.map((course, index) => { const points = course.grade ? gradePointsFor(course.grade) : null; const credits = Number(course.credits); const quality = points !== null && Number.isFinite(credits) && credits > 0 ? points * credits : null; return <fieldset key={course.id} className="grid gap-3 rounded-xl border border-border/60 p-3 md:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)_minmax(0,0.8fr)_minmax(0,0.8fr)_minmax(5rem,0.9fr)_3rem] md:items-end"><legend className="sr-only">Course row {index + 1}</legend><LabeledInput id={`course-name-${course.id}`} label="Course Name" value={course.name} onChange={(value) => updateCourse(course.id, 'name', value)} text /><div className="space-y-2"><Label htmlFor={`course-grade-${course.id}`} className="md:sr-only">Letter Grade</Label><select id={`course-grade-${course.id}`} value={course.grade} onChange={(event) => updateCourse(course.id, 'grade', event.target.value)} className="flex h-11 w-full rounded-md border border-input bg-background px-3 py-2 text-base focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><option value="">Select grade</option>{gpaScale.map(([letter, value]) => <option key={letter} value={letter}>{letter} ({value.toFixed(1)})</option>)}</select></div><LabeledInput id={`course-credits-${course.id}`} label="Credit Hours" value={course.credits} onChange={(value) => updateCourse(course.id, 'credits', value)} /><Output label="Grade Points" value={points === null ? '—' : points.toFixed(1)} /><Output label="Quality Points" value={quality === null ? '—' : quality.toFixed(2)} /><Button type="button" variant="outline" size="icon" className="h-11 w-full md:w-11" disabled={courses.length === 1} onClick={() => removeCourse(course.id)} aria-label={`Remove ${course.name || `course ${index + 1}`}`}><Trash2 className="h-4 w-4" aria-hidden="true" /></Button></fieldset>; })}</div><ActionButtons add={addCourse} load={loadExample} reset={reset} />{error && <ErrorMessage>{error}</ErrorMessage>}</section><SemesterResult result={result} /></div>;
}

function CumulativePanel({ source, setSource, previousGpa, setPreviousGpa, previousCredits, setPreviousCredits, manualGpa, setManualGpa, manualCredits, setManualCredits, semester, resultState, loadExample, reset }: { source: Source; setSource: (value: Source) => void; previousGpa: string; setPreviousGpa: (value: string) => void; previousCredits: string; setPreviousCredits: (value: string) => void; manualGpa: string; setManualGpa: (value: string) => void; manualCredits: string; setManualCredits: (value: string) => void; semester: SemesterGpaResult | null; resultState: { result: ReturnType<typeof calculateCumulativeGpa>; error: string | null; newGpa: number | null; newCredits: number | null }; loadExample: () => void; reset: () => void }) {
  return <div role="tabpanel" className="mt-6 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><section aria-label="Cumulative GPA inputs"><div className="grid gap-5 sm:grid-cols-2"><LabeledInput id="previous-gpa" label="Previous Cumulative GPA" value={previousGpa} onChange={setPreviousGpa} max="4" /><LabeledInput id="previous-credits" label="Previous Completed Credits" value={previousCredits} onChange={setPreviousCredits} /></div><fieldset className="mt-6 rounded-xl border border-border/60 p-4"><legend className="px-2 font-semibold">New semester values</legend><div className="grid gap-2 sm:grid-cols-2"><SourceButton selected={source === 'current'} onClick={() => setSource('current')}>Use Current Semester GPA{semester ? `: ${semester.gpa.toFixed(2)}` : ''}</SourceButton><SourceButton selected={source === 'manual'} onClick={() => setSource('manual')}>Enter Manually</SourceButton></div>{source === 'current' ? <p className="mt-4 text-sm leading-relaxed text-muted-foreground">{semester ? `Using ${semester.gpa.toFixed(2)} GPA across ${formatCredits(semester.totalCredits)} credits from Semester GPA mode.` : 'Load or enter valid courses in Semester GPA mode first.'}</p> : <div className="mt-5 grid gap-5 sm:grid-cols-2"><LabeledInput id="new-semester-gpa" label="New Semester GPA" value={manualGpa} onChange={setManualGpa} max="4" /><LabeledInput id="new-semester-credits" label="New Semester Credits" value={manualCredits} onChange={setManualCredits} /></div>}</fieldset><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Button type="button" onClick={loadExample}><Sparkles className="mr-2 h-4 w-4" aria-hidden="true" />Load Example</Button><Button type="button" variant="outline" onClick={reset}><RotateCcw className="mr-2 h-4 w-4" aria-hidden="true" />Reset</Button></div>{resultState.error && <ErrorMessage>{resultState.error}</ErrorMessage>}</section><section className="rounded-2xl bg-blue-50/70 p-5" aria-labelledby="cumulative-result" aria-live="polite"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Result</p><h2 id="cumulative-result" className="mt-2 text-xl font-bold">Your New Cumulative GPA</h2>{resultState.result ? <><p className="mt-5 text-4xl font-bold tracking-tight text-primary">{resultState.result.gpa.toFixed(2)}</p><dl className="mt-6 grid gap-3 sm:grid-cols-2"><ResultItem label="Previous GPA" value={Number(previousGpa).toFixed(2)} /><ResultItem label="New Semester GPA" value={(resultState.newGpa as number).toFixed(2)} /><ResultItem label="Total Completed Credits" value={formatCredits(resultState.result.totalCredits)} /><ResultItem label="Combined Quality Points" value={(resultState.result.previousQualityPoints + resultState.result.newQualityPoints).toFixed(2)} /></dl></> : <p className="mt-4 leading-relaxed text-muted-foreground">Enter valid previous and new semester values to calculate cumulative GPA.</p>}</section></div>;
}

function SemesterResult({ result }: { result: SemesterGpaResult | null }) { return <section className="rounded-2xl bg-blue-50/70 p-5" aria-labelledby="semester-result" aria-live="polite"><p className="text-sm font-semibold uppercase tracking-wider text-primary">Result</p><h2 id="semester-result" className="mt-2 text-xl font-bold">Your Semester GPA</h2>{result ? <><p className="mt-5 text-4xl font-bold tracking-tight text-primary">{result.gpa.toFixed(2)}</p><dl className="mt-6 grid gap-3"><ResultItem label="Total Credits" value={formatCredits(result.totalCredits)} /><ResultItem label="Total Quality Points" value={result.totalQualityPoints.toFixed(2)} /></dl></> : <p className="mt-4 leading-relaxed text-muted-foreground">Enter at least one valid course, letter grade and positive credit value to calculate GPA.</p>}</section>; }
function ModeTab({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" role="tab" aria-selected={selected} onClick={onClick} className={`min-h-12 rounded-lg px-2 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:px-4 ${selected ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}>{children}</button>; }
function SourceButton({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" aria-pressed={selected} onClick={onClick} className={`min-h-11 rounded-lg border px-3 py-2 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selected ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-background hover:bg-accent'}`}>{children}</button>; }
function LabeledInput({ id, label, value, max = String(maximumCredits), onChange, text = false }: { id: string; label: string; value: string; max?: string; onChange: (value: string) => void; text?: boolean }) { return <div className="space-y-2"><Label htmlFor={id} className={id.startsWith('course-') ? 'md:sr-only' : ''}>{label}</Label><Input id={id} type={text ? 'text' : 'number'} inputMode={text ? undefined : 'decimal'} min={text ? undefined : '0'} max={text ? undefined : max} step={text ? undefined : 'any'} value={value} onChange={(event) => onChange(event.target.value)} className="h-11 text-base" /></div>; }
function Output({ label, value }: { label: string; value: string }) { return <div><span className="mb-2 block text-sm font-medium md:sr-only">{label}</span><output className="flex h-11 items-center rounded-md bg-secondary/50 px-3 font-semibold">{value}</output></div>; }
function ResultItem({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-background p-4"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-1 text-lg font-bold">{value}</dd></div>; }
function ActionButtons({ add, load, reset }: { add: () => void; load: () => void; reset: () => void }) { return <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Button type="button" onClick={add}><Plus className="mr-2 h-4 w-4" aria-hidden="true" />Add Course</Button><Button type="button" variant="outline" onClick={load}><Sparkles className="mr-2 h-4 w-4" aria-hidden="true" />Load Example</Button><Button type="button" variant="outline" onClick={reset}><RotateCcw className="mr-2 h-4 w-4" aria-hidden="true" />Reset</Button></div>; }
function ErrorMessage({ children }: { children: React.ReactNode }) { return <p role="alert" className="mt-5 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm font-medium text-destructive">{children}</p>; }
function validateCourse(course: CourseRow) { if (!course.grade || course.credits.trim() === '') return 'Select a grade and enter credit hours.'; const credits = Number(course.credits); if (!Number.isFinite(credits)) return 'Enter valid numeric credit hours.'; if (credits <= 0) return 'Credit hours must be greater than zero.'; if (credits > maximumCredits) return `Credit hours must be no more than ${maximumCredits.toLocaleString()}.`; return null; }
function validateCumulativeBase(gpaText: string, creditsText: string) { if (gpaText.trim() === '' || creditsText.trim() === '') return 'Enter previous cumulative GPA and completed credits.'; const gpa = Number(gpaText); const credits = Number(creditsText); if (!Number.isFinite(gpa) || gpa < 0 || gpa > 4) return 'Previous cumulative GPA must be between 0 and 4.0.'; if (!Number.isFinite(credits) || credits < 0 || credits > maximumCredits) return `Previous completed credits must be between 0 and ${maximumCredits.toLocaleString()}.`; return null; }
function validateManualSemester(gpaText: string, creditsText: string) { if (gpaText.trim() === '' || creditsText.trim() === '') return 'Enter new semester GPA and credits.'; const gpa = Number(gpaText); const credits = Number(creditsText); if (!Number.isFinite(gpa) || gpa < 0 || gpa > 4) return 'New semester GPA must be between 0 and 4.0.'; if (!Number.isFinite(credits) || credits <= 0 || credits > maximumCredits) return `New semester credits must be greater than zero and no more than ${maximumCredits.toLocaleString()}.`; return null; }
function formatCredits(value: number) { return new Intl.NumberFormat(undefined, { maximumFractionDigits: 4 }).format(value); }
